SELECT DISTINCT 
	(SELECT COUNT(NR_PARTIDA) 
		FROM PARTIDAS 
		WHERE VENCEDOR IS NOT NULL 
		AND (JOGADOR_1 = :NR_JOGADOR OR JOGADOR_2 = :NR_JOGADOR)
	) AS TOTAL_DISPUTAS,
	(SELECT COUNT(NR_PARTIDA) 
		FROM PARTIDAS 
		WHERE VENCEDOR = :NR_JOGADOR
	) AS VITORIAS,
	(SELECT COUNT(NR_PARTIDA) 
		FROM PARTIDAS 
		WHERE (JOGADOR_1 = :NR_JOGADOR OR JOGADOR_2 = :NR_JOGADOR) 
		AND VENCEDOR != :NR_JOGADOR 
		AND VENCEDOR IS NOT NULL
	) AS DERROTAS	
FROM PARTIDAS;
