SELECT 
	NR_JOGADOR,
	APELIDO,
	EMAIL,
	DT_CADASTRO, 
	NOME,
	TO_CHAR(DT_NASCIMENTO,'DD/MM/YYYY') AS DT_NASCIMENTO,
	UF,
	CIDADE,
	(SELECT COUNT(NR_PARTIDA) 
		FROM PARTIDAS 
		WHERE VENCEDOR = :NR_JOGADOR
	) - (SELECT COUNT(NR_PARTIDA) 
		FROM PARTIDAS 
		WHERE (JOGADOR_1 = :NR_JOGADOR OR JOGADOR_2 = :NR_JOGADOR) 
		AND VENCEDOR != :NR_JOGADOR 
		AND VENCEDOR IS NOT NULL
	) AS PONTOS
FROM JOGADORES WHERE NR_JOGADOR = :NR_JOGADOR;