SELECT 
	PARTIDAS.NR_PARTIDA AS NR_PARTIDA,
	JOGADORES.APELIDO AS ADVERSARIO,
	PARTIDAS.VENCEDOR AS VENCEDOR
FROM PARTIDAS
INNER JOIN JOGADORES ON (PARTIDAS.JOGADOR_2 = JOGADORES.NR_JOGADOR OR PARTIDAS.JOGADOR_1 = JOGADORES.NR_JOGADOR)
WHERE (JOGADOR_1 = :NR_JOGADOR OR JOGADOR_2 = :NR_JOGADOR) AND JOGADORES.NR_JOGADOR != :NR_JOGADOR
ORDER BY PARTIDAS.NR_PARTIDA DESC;